spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://localhost:5432/carddb
    username: carddb_user
    password: root
    driver-class-name: org.postgresql.Driver
  cloud:
    loadbalancer:
      retry:
        enabled: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: basic

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

server:
  port: 8020

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    prefer-ip-address: true

